[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-dev", "build-essential"]

[phases.build]
cmds = ["pip3 install --upgrade pip", "pip3 install -r requirements.txt"]

[start]
cmd = "python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT" 