[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-dev", "build-essential"]

[phases.build]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT" 