[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-dev", "build-essential"]
nixPkgs = ["python310"]

[phases.install]
cmds = ["python -m pip install --upgrade pip"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT" 